name: Go package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
            go get .
      
      - name: Build
        run: go build -v ./...

      - name: list all
        run: ls

      - name: Build the Docker image
        run: >
          docker buildx build . 
          --file Dockerfile
          --build-arg PROJECT_VERSION="$PROJECT_VERSION"
          --tag bisento1119/kub-train-go-be-a:$(date +%s)

          

